name: AssetStudioBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      


      - name: Nuget Restore
        run: nuget restore
      
      - name: Build .Net472
        run: msbuild /p:Configuration=Release /p:TargetFramework=net472 /verbosity:minimal

      - name: Build .Net10
        run: msbuild /t:AssetStudioGUI:publish /p:Configuration=Release /p:TargetFramework=net10.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Upload .Net472 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AssetStudio.net472
          path: AssetStudioGUI/bin/Release/net472

      - name: Upload .Net10 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AssetStudio.net10
          path: AssetStudioGUI/bin/Release/net10.0-windows/publish
